#!/bin/sh
# microjs8-enable-display — enable the ST7789V SPI display overlay
# in /boot/firmware/config.txt for bare Raspberry Pi installs.
#
# Phase 17: shipped by the microjs8 .deb as a convenience for bare
# Pi Zero 2 W operators wiring up a 1.9" 170x320 ST7789V/V2 panel
# (Waveshare module or compatible). Skip this on CardputerZero —
# its kernel already provides /dev/fb1 via the on-board display
# driver, no config.txt edit needed.
#
# Safety:
#   - Backs up config.txt before editing (timestamped copy)
#   - Idempotent (won't add duplicate lines if rerun)
#   - Refuses to run if config.txt is missing OR doesn't look like
#     a Pi boot config (defensive: not safe to blindly edit if
#     we're not on a Pi)
#   - Prints diff before applying (operator confirms with Y)
#   - Reminds operator to reboot
#
# Usage:
#   sudo microjs8-enable-display          # interactive
#   sudo microjs8-enable-display --yes    # non-interactive (CI/scripted)
#   sudo microjs8-enable-display --revert  # remove what we added (uses backup)
#
# Defaults match the Waveshare 1.9" 170x320 ST7789V2 module on a Pi
# Zero 2 W. Customize the GPIO pin assignments below if you wired
# DC/RST/BL differently — they match the conventional Waveshare
# Pi pinout (DC=GPIO25, RST=GPIO27, BL=GPIO18).

set -eu

CONFIG_PATH="/boot/firmware/config.txt"
LEGACY_PATH="/boot/config.txt"   # pre-Bookworm location

# ── Locate the config file ─────────────────────────────────────────
# Bookworm moved /boot/config.txt → /boot/firmware/config.txt.
# Support both so this script works on older images too.
if [ -f "$CONFIG_PATH" ]; then
    CONFIG="$CONFIG_PATH"
elif [ -f "$LEGACY_PATH" ]; then
    CONFIG="$LEGACY_PATH"
else
    echo "error: cannot find Pi boot config.txt at $CONFIG_PATH or $LEGACY_PATH" >&2
    echo "are you running this on a Raspberry Pi?" >&2
    exit 1
fi

# ── Sanity check: is this actually a Pi boot config? ───────────────
# A real Pi config.txt has at least one [pi*], dtparam=, or dtoverlay=
# line. Reject otherwise — we don't want to scribble on something
# that isn't ours.
if ! grep -qE '^\[(pi|all)|^dtparam=|^dtoverlay=|^arm_64bit=' "$CONFIG"; then
    echo "error: $CONFIG doesn't look like a Pi boot config" >&2
    echo "(no [pi*], dtparam=, dtoverlay=, or arm_64bit= lines found)" >&2
    exit 1
fi

# ── Parse args ─────────────────────────────────────────────────────
NONINTERACTIVE=0
REVERT=0
while [ $# -gt 0 ]; do
    case "$1" in
        --yes|-y)
            NONINTERACTIVE=1
            shift
            ;;
        --revert)
            REVERT=1
            shift
            ;;
        --help|-h)
            sed -n '2,/^#$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "error: unknown argument: $1" >&2
            echo "usage: $0 [--yes] [--revert]" >&2
            exit 1
            ;;
    esac
done

# ── Need root ──────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "error: must run as root (try: sudo $0)" >&2
    exit 1
fi

# ── The block we add ───────────────────────────────────────────────
# A clearly-delimited block, so a future --revert can find and
# remove exactly what we added (vs editing operator hand-edits).
BLOCK_START="# >>> microjs8-enable-display BEGIN (do not edit between markers)"
BLOCK_END="# <<< microjs8-enable-display END"

read_only_block() {
    cat << 'BLOCK_EOF'
# >>> microjs8-enable-display BEGIN (do not edit between markers)
# Enable SPI bus + ST7789V framebuffer driver for the 1.9" 170x320
# panel. Generated by microjs8-enable-display.
#
# If colors are wrong, add ',bgr=true' to the dtoverlay line below.
# If image is shifted by ~35 pixels horizontally, add ',width_offset=35'
# (some panels need this; Waveshare 1.9" typically doesn't).
# If image is rotated wrong, change 'rotate=90' (try 0, 90, 180, 270).
dtparam=spi=on
dtoverlay=fb_st7789v,rotate=90,speed=40000000,fps=30,width=320,height=170,reset_pin=27,dc_pin=25,led_pin=18
# <<< microjs8-enable-display END
BLOCK_EOF
}

# ── Revert path ────────────────────────────────────────────────────
if [ "$REVERT" -eq 1 ]; then
    if ! grep -qF "$BLOCK_START" "$CONFIG"; then
        echo "no microjs8-enable-display block found in $CONFIG — nothing to revert"
        exit 0
    fi
    backup="${CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"
    cp -p "$CONFIG" "$backup"
    echo "backed up to $backup"
    # Delete from BEGIN marker through END marker, inclusive.
    sed -i "/$(echo "$BLOCK_START" | sed 's:[][\/.^$*]:\\&:g')/,/$(echo "$BLOCK_END" | sed 's:[][\/.^$*]:\\&:g')/d" "$CONFIG"
    echo "removed microjs8 display block from $CONFIG"
    echo "reboot required for the change to take effect:"
    echo "  sudo reboot"
    exit 0
fi

# ── Idempotency check ──────────────────────────────────────────────
if grep -qF "$BLOCK_START" "$CONFIG"; then
    echo "microjs8-enable-display block already present in $CONFIG — nothing to do"
    echo "if you want to change the overlay, edit $CONFIG manually OR run:"
    echo "  sudo $0 --revert"
    echo "  sudo $0          # re-add with current defaults"
    exit 0
fi

# ── Preview the change ─────────────────────────────────────────────
echo
echo "About to append the following block to $CONFIG:"
echo
read_only_block | sed 's/^/  /'
echo

if [ "$NONINTERACTIVE" -ne 1 ]; then
    printf "Proceed? [y/N] "
    read -r reply
    case "$reply" in
        y|Y|yes|YES) ;;
        *)
            echo "aborted; no changes made."
            exit 1
            ;;
    esac
fi

# ── Apply ──────────────────────────────────────────────────────────
backup="${CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"
cp -p "$CONFIG" "$backup"
echo "backed up to $backup"

# Append, ensuring a leading newline if the file doesn't end in one.
if [ -n "$(tail -c1 "$CONFIG")" ]; then
    printf '\n' >> "$CONFIG"
fi
read_only_block >> "$CONFIG"
echo "added microjs8 display block to $CONFIG"
echo
echo "Reboot required for the kernel to load the overlay:"
echo "  sudo reboot"
echo
echo "After reboot, verify with:"
echo "  ls /dev/fb*                                # expect /dev/fb1"
echo "  dmesg | grep -i st7789                     # expect successful init"
echo "  sudo cat /dev/urandom > /dev/fb1           # smoke test (Ctrl+C to stop)"
